### ISSUE TITLE
If kubemci changes a service, ingress-gce won't notice that

### ISSUE THREAD

**Issue by G-Harmon** [GoogleCloudPlatform/k8s-multicluster-ingress#104]
@nicksardo reported a potential bug in the interaction between kubemci and ingress-gce:
"When a service change is observed, it normally scans through all ingresses to determine whether it should enqueue the ingress for sync.
It only checks GCEIngress, not GCEMultiClusterIngress"
In this code: 
https://github.com/kubernetes/ingress-gce/blob/master/pkg/controller/controller.go#L192-L205

I don't think we change the service, but I wanted @nikhiljindal or @csbell to verify this.

**Comment by nikhiljindal** [comment]
1. kubemci never changes any service. User can update the service.

2. When user updates the service, yes we do not enque multucluster ingress again. Even if we did enque multi cluster ingresses, ingress-gce wont do anything. It manages instance groups only.
Users will need to run `kubemci create` again to update healthcheck, urlmap or other resources.

So while there is no harm in enqueuing multicluster ingresses, we wont gain anything either.

**Comment by nikhiljindal** [comment]
Closing as I dont think we need to do anything here. Feel free to reopen if required.
