### ISSUE TITLE
Add an e2e test for custom health checks

### ISSUE THREAD

**Issue by nikhiljindal** [GoogleCloudPlatform/k8s-multicluster-ingress#108]
Now that we have the e2e test setup (https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/issues/48#issuecomment-352619909), we need to add more test cases.

One of them is to add a test case for custom health check support that was added in https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/pull/72

**Comment by nikhiljindal** [comment]
@glindste feel free to take this up if interested.
Will help us ensure that we do not regress :)

**Comment by glindste** [comment]
Sure, I can pick it up :)

**Comment by nikhiljindal** [comment]
Thanks @glindste 
Feel free to ping me if you have any questions!
