### ISSUE TITLE
Allow replacing the ingress resource with --force

### ISSUE THREAD

**Issue by glindste** [GoogleCloudPlatform/k8s-multicluster-ingress#109]
If a change is made to the ingress definition and then create is run again with the `--force` flag, the ingress resource in the clusters is not updated. A specific issue that arises is that if you add a new backend service with a different nodeport, the instance groups (that are managed by the ingress-gce controller) are not updated with the required named ports.

I have a local fix that I might polish into a PR but I figured it's good to track the issue in case I don't have time for that.

**Comment by nikhiljindal** [comment]
ah good catch @glindste 
Yes we should absolutely fix this.

PR would be awesome!
