### ISSUE TITLE
Ignore NotFound errors when deleting GCE resources

### ISSUE THREAD

**Issue by nicksardo** [GoogleCloudPlatform/k8s-multicluster-ingress#119]
Following up on https://github.com/kubernetes/kubernetes/issues/54717, the GCE wrapper functions will no longer capture and ignore NotFound errors. As I mentioned in https://github.com/kubernetes/kubernetes/pull/54746#issuecomment-352911385, it seems that the only callers missing this check are in this repo. Recommend auditing all resource deletion calls prior to updating your vendor.

Ping me if you're too busy for this and I'll shoot you a PR.

cc @bowei

**Comment by G-Harmon** [comment]
cc me.

**Comment by nikhiljindal** [comment]
Hey @nicksardo 
Thanks for filing this.

Would love to have your first kubemci PR :)

**Comment by G-Harmon** [comment]
Nikhil, I said that we (I) could do this.

**Comment by nikhiljindal** [comment]
Cool

**Comment by nikhiljindal** [comment]
Fixed in https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/pull/140
