### ISSUE TITLE
FW rules are wrong on non-default network

### ISSUE THREAD

**Issue by brndnmtthws** [GoogleCloudPlatform/k8s-multicluster-ingress#134]
If a cluster isn't in the `default` network, the healthcheck firewall rule won't work because it uses the implicit default of `default`.

I fixed it for now by manually adding another firewall rule.

**Comment by nikhiljindal** [comment]
Thanks for filing the issue @brndnmtthws 
Dup of https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/issues/121?

**Comment by brndnmtthws** [comment]
Woops, didn't see that issue. Yeah it's a dupe.

**Comment by nikhiljindal** [comment]
Thanks for confirming
