### ISSUE TITLE
Allow creation of Ingresses in default namespace

### ISSUE THREAD

**Issue by G-Harmon** [GoogleCloudPlatform/k8s-multicluster-ingress#17]
As it stands, one must include a namespace in the ingress yaml file. We should detect the case where no namespace is provided, and use the default namespace.

The tool currently gives this error if no namespace is specified:
Error in creating load balancer: error in creating ingress in cluster my-cluster-name: an empty namespace may not be set during creation

**Comment by csbell** [comment]
Fixed by #34
