### ISSUE TITLE
ingress creation hangs on "Waiting for ingress"

### ISSUE THREAD

**Issue by OlivierBoucher** [GoogleCloudPlatform/k8s-multicluster-ingress#170]
Hi,

I tried creating an ingress as per the zone printer guidelines, however it seemed to hang forever printing the same output:

```
Waiting for ingress ( default : tracking-dev-ingress ) to get ingress.gcp.kubernetes.io/instance-groups annotation.....
```

I killed the command after ~ 5 mins. Here is the full log of the second time I ran the command

[result.log](https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/files/1872112/result.log)

I can provide more context on demand, I don't see any errors to guide me.

Thanks

EDIT: my bad there, just realized one of the cluster was on 1.7.x. Will update or close the issue if its OK

**Comment by OlivierBoucher** [comment]
Was indeed my bad -- wrong cluster version. Sorry guys

**Comment by G-Harmon** [comment]
FYI, I'm adding a cluster version check in the open PR #167, so hopefully this failure mode will be avoided in the future.
