### ISSUE TITLE
Coveralls' reported coveraged dropped from 60% to 5%

### ISSUE THREAD

**Issue by G-Harmon** [GoogleCloudPlatform/k8s-multicluster-ingress#190]
On April 6, Coveralls reported coverage went down from:
GoogleCloudPlatform/k8s-multicluster-ingress First build on master at 59.527% for commit: Merge +refs/pull/183/head:refs/pr/183 by K8S Bootstrap
to:
GoogleCloudPlatform/k8s-multicluster-ingress First build on master at 5.347% for commit: Merge +refs/pull/189/head:refs/pr/189 by K8S Bootstrap

I don't know what happened that it stopped seeing as much coverage. Seems like it must be a configuration problem.
cc @nikhiljindal @BenTheElder

**Comment by G-Harmon** [comment]
This is the coverage site: https://coveralls.io/github/GoogleCloudPlatform/k8s-multicluster-ingress

**Comment by BenTheElder** [comment]
I'm not familiar with coveralls internals but nothing interesting should have changed on the test-infra side of things WRT to this.

**Comment by G-Harmon** [comment]
Should be fixed by #200.
