### ISSUE TITLE
error when running kubemci create ~~

### ISSUE THREAD

**Issue by myguddy** [GoogleCloudPlatform/k8s-multicluster-ingress#198]
In GKE, k8s is 1.9.7-gke.3

running this command to create lb
kubemci create global-lb \
    --ingress=./yaml/ing.yaml \
    --gcp-project=autocomplete-210003 \
    --kubeconfig=~/.kubemci

Error is
"Error: Error in creating load balancer: error in creating cloud interface: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information."

I loggin as owner

Is this bug or I missed something to permission?

**Comment by myguddy** [comment]
It is the name of config file " .kubemci"

I changed the name of this, then works fine.

**Comment by G-Harmon** [comment]
Glad you got this to work.
I'm guessing the problem is that "~" expansion doesn't work when being passed to a lot of commands?
