### ISSUE TITLE
`kubemci create` info text for named ports should print formatted named ports

### ISSUE THREAD

**Issue by madhusudancs** [GoogleCloudPlatform/k8s-multicluster-ingress#20]
`kubemci create` info text prints Go struct that contains pointers for named ports.

```shell
Fetched instance group: us-east4-a/k8s-ig--72ba3ab13eeabf69, got named ports: []*compute.NamedPort{(*compute.NamedPort)(0xc4203d57c0), (*compute.NamedPort)(0xc4203d5810)}Ensuring backend services
```

We should instead print a formatted text.

**Comment by G-Harmon** [comment]
This was fixed in commit https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/commit/73b54c6b975e136fc47d7e930df5ed00e198c36a
