### ISSUE TITLE
UDP Load Balancing and TCP load Balancing with kubeMCI 

### ISSUE THREAD

**Issue by assafsauer** [GoogleCloudPlatform/k8s-multicluster-ingress#203]
is it possible to run “kubemci create” with  UDP Load Balancing or TCP load Balancing ? 
or only HTTP/s Load Balancing is supported.

**Comment by nikhiljindal** [comment]
kubemci supports HTTP/s load balancing only.

Will love to understand why you need UDP or TCP load balancing.
Will be great if you can explain your use case at https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/issues/197 which has more details.

Thanks!

**Comment by nikhiljindal** [comment]
Closing as dup
