### ISSUE TITLE
Adding or removing single cluster to load balancer pool

### ISSUE THREAD

**Issue by KamiMay** [GoogleCloudPlatform/k8s-multicluster-ingress#205]
Hello, I was looking for some instructions how to add or remove single cluster from the load balanced pool, but failed to do so. Is it possible to do without recreating load balancer with new cluster list? 

Thanks

**Comment by nikhiljindal** [comment]
https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/issues/58 and https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/pull/146 have more information on the remove-clusters command.
