### ISSUE TITLE
Anyone use this example w/ Cloudflare?

### ISSUE THREAD

**Issue by lolcoolkat** [GoogleCloudPlatform/k8s-multicluster-ingress#208]
Trying to get this example to work, howerver; I'm having issues after deploying w/ my origin certificate from Cloudflare. I just get a 502 server error after waiting for about 10 minutes. :/

Anyone here get this example working w/ Cloudflare SSL/HTTPS ? :) Thanks!

**NOTE**: If anyone has successfully done it.. would anyone mind sharing a link to a repo that has the files that worked for you!

**Comment by G-Harmon** [comment]
I doubt I'll be of much help, but you should post more details about your setup and steps taken.

**Comment by lolcoolkat** [comment]
@G-Harmon @nikhiljindal Any ideas to what I could be doing wrong? It has to be a silly mistake 😞
