### ISSUE TITLE
How to debug "failed_to_pick_backend"

### ISSUE THREAD

**Issue by thezjy** [GoogleCloudPlatform/k8s-multicluster-ingress#215]
I deployed [hasura graphql engine](https://docs.hasura.io/1.0/graphql/manual/deployment/kubernetes/index.html) following the guide. Everything works fine except the endpoint keeps returning 502 (I've waited long enough).
Logs of load balancer show the error is `failed_to_pick_backend`. How can I debug this problem?

**Comment by thezjy** [comment]
The deployment works in a single cluster. The only difference between it and the zoneprinter sample I can see is that hasura uses 8080 containerPort. Does it matter?

**Comment by pdecat** [comment]
`failed_to_pick_backend` means that no backend responds to health checks with an HTTP 200 status.
You should start by checking the health check configuration on the load balancer.

**Comment by thezjy** [comment]
Thanks a lot. Changed the health check configuration and everything works ok!
