### ISSUE TITLE
Support for managed certificates

### ISSUE THREAD

**Issue by oceanful** [GoogleCloudPlatform/k8s-multicluster-ingress#229]
From what I can tell, `kubemci` supports pre-shared and secret certs, but does not support [Google-managed SSL certificates](https://cloud.google.com/kubernetes-engine/docs/how-to/managed-certs).

If my understanding correct, is there a workaround for making managed certificates work? I tried manually editing the Load balancer's Frontend configuration to include the HTTPS protocol and certs, but it didn't work; I assume there's more setup that needs to be done like the HTTPS target proxy and forwarding rules.

I'm happy to contribute if you can point me in the right direction. Thank you!

**Comment by oceanful** [comment]
Ah, I see a workaround referenced here: https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/issues/141#issuecomment-432216498

Feel free to close this issue if you want to consolidate, or leave it open if you want to address managed certificates separately.

**Comment by nikhiljindal** [comment]
Yes kubemci supports using Google managed SSL certs via the pre-shared-cert annotation.

Please let us know if you run into any other issues.

Would also love to get your feedback on https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/issues/117 once you have everything setup.
