### ISSUE TITLE
kubemci commands have a litany of testing flags

### ISSUE THREAD

**Issue by perotinus** [GoogleCloudPlatform/k8s-multicluster-ingress#39]
This is due to `k8s.io/ingress-gce/pkg/loadbalancers` having a dependency on the `testing` package. This needs to be fixed, and that repo revendored.

- [x] Remove `k8s.io/ingress-gce/pkg/loadbalancers` dependency on `testing` package.
- [x] Revendor `k8s.io/ingress-gce/pkg/loadbalancers`

**Comment by nikhiljindal** [comment]
Thanks for finding this out @perotinus!
Sent https://github.com/kubernetes/ingress-gce/pull/69 to remove `ingress-gce/pkg/loadbalancers` dependency on `testing`

**Comment by nikhiljindal** [comment]
This is now fixed.
