### ISSUE TITLE
Better input validation

### ISSUE THREAD

**Issue by nikhiljindal** [GoogleCloudPlatform/k8s-multicluster-ingress#53]
We should do better validation upfront.
We also assume a few things, like it is upto the user to ensure that there is a default backend service in the ingress spec and that there exists a service in all clusters and that they have the same node ports in all clusters.
We should check for these things.
We can always perform the checks or hide them behind a `--validate` flag.

Concrete list:
- [x] Ingress spec should have a default backend service
- [x] Services mentioned in the ingress spec should exist in all clusters in the same namespace
- [x] A particular service should have the same nodeport in all clusters
- [x] All clusters should be of version > 1.8.1

**Comment by nikhiljindal** [comment]
Mismatching node ports in clusters is particularly bad and common tripping point for users.
Our current help message does not help either:
```
could not find matching nodeport for backend {echoheaders {0 80 }} and service default/echoheaders. Looking for port {0 80 } in []
```

**Comment by G-Harmon** [comment]
maybe also check version number >= 1.8.1

**Comment by nikhiljindal** [comment]
Updated the description to have a concrete list.
For `validate` flag: I think we should do these validations by default. User can turn them off by setting --`validate=false`.

Some more questions:
* Should setting --force=true, set --validate=false i.e allow users to perform the operation even if some validations are failing?
I think requiring users to explicitly set both is better.
* The validation scenarios discussed above make sense for create. Do we need the same for other commands like delete and remove-clusters?
I think starting with validations for create only is better. We can add validations for other commands based on user feedback.

cc @mdelio What do you think?
Feel free to add anything I might have missed in the list above.

**Comment by G-Harmon** [comment]
> Ingress spec should have a default backend service
This is already checked for here:
https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/blob/master/app/kubemci/pkg/gcp/urlmap/urlmapsyncer.go#L251

**Comment by G-Harmon** [comment]
Okay, we've covered all of these validations. Closing.
