### ISSUE TITLE
Provide binary release

### ISSUE THREAD

**Issue by rvrignaud** [GoogleCloudPlatform/k8s-multicluster-ingress#73]
Hello,

In order to ease the test of kubemci and increase number of feedbacks could you please provide a binary release ?

Thanks in advance,
Cheers

**Comment by nikhiljindal** [comment]
Sure. Its available for download at 
`https://storage.googleapis.com/kubemci-release/release/v0.0.1/bin/linux/amd64/kubemci`.
Let me know if linux amd64 does not work for you and you need a different distribution. Will be happy to generate it.

Have also included the link in release documentation: https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/releases/tag/0.0.1

**Comment by mdelio** [comment]
Hi Romain, we'd like to include you (and others) in the early access program if possible.  Could you sign up for the EAP using this form, and we'll follow-up with more info?
https://goo.gl/forms/RHg032DrRnnqF0by1

**Comment by rvrignaud** [comment]
Hi @nikhiljindal,

Thank you for your really fast reply. As this is intended to be used as a CLI, I think people would be also interested with darwin build as lots of developers are using MacOS.

Thanks for your help.

**Comment by samanthakem** [comment]
Hi @nikhiljindal, I would like a binary release for MacOS.

**Comment by nikhiljindal** [comment]
We released the next version for kubemci (v0.1.1) just now and I have generated both linux and darwin binaries this time.

Binaries available for download at:
Linux, amd64: https://storage.googleapis.com/kubemci-release/release/v0.1.1/bin/linux/amd64/kubemci
darwin (MacOSX), amd64: https://storage.googleapis.com/kubemci-release/release/v0.1.1/bin/darwin/amd64/kubemci


@rvrignaud and @samanthakem Would love to get your feedback as you try it out!

**Comment by rvrignaud** [comment]
Hi @nikhiljindal,

Thanks for the binaries. I'll provide feedbacks in another issue.
Closing this one
