### ISSUE TITLE
gcp-project should be an optional flag

### ISSUE THREAD

**Issue by nikhiljindal** [GoogleCloudPlatform/k8s-multicluster-ingress#80]
We should auto detect the project from gcloud config

**Comment by nikhiljindal** [comment]
We do it in our e2e tests now: https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/blob/9576cb41596031cdd88d04321497f12870a7510a/test/e2e/cases/utils.go#L272.

Should be easy to add that logic to the main code as well

**Comment by G-Harmon** [comment]
Fixed with #172 and #176.
